version: '3'

services:
    reverse:
        image: jwilder/nginx-proxy:latest
        ports:
        - 80:80
        - 443:443
        volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro

    docker:
        environment:
            - VIRTUAL_HOST=docker.behemythic.com
        image: registry:latest
        volumes:
            - /mnt/gluster/registry/data:/var/lib/registry
            - /mnt/gluster/registry/certs:/certs
            - /mnt/gluster/registry/auth:/auth
        ports:
            - 5000:5000

    artifactory:
        environment:
            - VIRTUAL_HOST=artifactory.behemythic.com
        image: docker.bintray.io/jfrog/artifactory-cpp-ce:latest
        volumes:
            - /mnt/gluster/artifactory/var/:/var/opt/jfrog/artifactory
        ports:
            - 8081:8081
            - 8082:8082