version: '3'

services:
    reverse:
        image: jwilder/nginx-proxy:alpine
        ports:
        - 80:80
        - 443:443
        volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro

    artifactory:
        environment:
            - JFROG_HOME=/opt/jfrog
            - VIRTUAL_HOST=artifactory.behemythic.com

        image: docker.bintray.io/jfrog/artifactory-cpp-ce:latest
        volumes:
            - ${JFROG_HOME}/artifactory/var/:/var/opt/jfrog/artifactory
        ports:
            - 8081:8081
            - 8082:8082
