version: '3.8'

services:
    traefik:
        image: traefik:latest
        command:
            - --entrypoints.web.address=:80
            - --entrypoints.web-secured.address=:443
            - --providers.docker.exposedbydefault=false
            - --providers.docker=true
            - --providers.docker.swarmMode=true
        ports:
            - 80:80
            - 443:443
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
        deploy:
            placement:
                constraints:
                    - "node.labels.arch==amd64"
            labels:
                - "traefik.enable=true"

    conan:
        image: conanio/conan_server:latest
        labels:
            - "traefik.http.routers.conan.rule=Host(`conan.behemythic.com`)"
            - "traefik.http.services.conan.loadBalancer.server.port=9300"
        deploy:
            placement:
                constraints:
                    - "node.labels.arch==amd64"

    minecraft:
        image: itzg/minecraft--server:latest
        environment:
            - SERVER_NAME=Behemythical
            - ENABLE_RCON=false
            - EULA=TRUE
            - GAMEMODE=survival
            - DIFFICULTY=hard
            - VIEW_DISTANCE=12
        volumes:
            - minecraft-data:/data
        stdin_open: true
        tty: true
        labels:
            - "traefik.http.routers.minecraft.rule=Host(`minecraft.behemythic.com`)"
            - "traefik.http.services.minecraft.loadBalancer.server.port=25565"
        deploy:
            placement:
                constraints:
                    - "node.labels.arch==amd64"

volumes:
    minecraft-data: