[project]
authors = [
  {name = "Asher Norland", email = "asher.norland@gmail.com"},
] 
description = "Ansible roles for my homelab" 
dynamic = ["version"] 
license = "MIT" 
name = "homelab" 
readme = "README.md" 
requires-python = ">=3.12" # Pinned to Ubuntu 24 version

dependencies = [
  "ansible-vault>=4.1.0",
  "pydantic>=2.11.7",
  "pyyaml>=6.0.2",
  "ansible-dev-tools>=25.5.2",
]

[project.urls]
homepage = "https://github.com/Behemyth/homelab"
repository = "https://github.com/Behemyth/homelab"

[project.optional-dependencies]
docs = [
  "mkdocs-material>=9.6.14",
]
[dependency-groups]
lint = [
  "ruff>=0.12.1",
  "pyrefly>=0.22.0",
]
test = [
  "pytest>=8.4.1",
  "pytest-mock>=3.14.1",
]

[tool.setuptools]
py-modules = []

[tool.pytest.ini_options]
addopts = "-v"
log_cli = true
testpaths = [
  "tests",
]

[tool.pyrefly]
project-includes = ["tests"]

[tool.ruff]
line-length = 120
preview = true

[tool.ruff.lint]
ignore = [
  "D206",
  "D300",
  "D415",
  "E111",
  "E114",
  "E117",
]
select = [
  "D", # pydocstyle
  "F", # Pyflakes
  "I", # isort
  "PL", # pylint
  "UP", # pyupgrade
  "E", # pycodestyle
  "B", # flake8-bugbear
  "SIM", # flake8-simplify
  "PT", # flake8-pytest-style
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
docstring-code-format = true
indent-style = "space"
quote-style = "single"

[tool.coverage.report]
skip_empty = true

[tool.pdm.version]
source = "scm"

[tool.pdm.scripts]
analyze = "ruff check tests"
ansible-lint = "ansible-lint"
build-docs = 'mkdocs build --strict'
dev = 'mkdocs serve'
format = "ruff format"
lint = {composite = ["analyze", "format", "type-check", "ansible-lint"]}
setup = "ansible-playbook -i inventory/localhost.yml playbooks/setup.yml -K"
test = "pytest tests"
test-integration = "pytest tests/integration"
test-unit = "pytest tests/unit"
type-check = "pyrefly check"

[tool.pdm]
distribution = false
