[project]
description = "Home server package"
name = "infra"

authors = [
  {name = "Asher Norland", email = "asher.norland@gmail.com"},
]
license = {text = "MIT"}
readme = "README.md"

dynamic = ["version"]

requires-python = ">=3.12" # Pinned to Ubuntu 24 version

dependencies = [
  "ansible-core>=2.18.1",
  "ansible-vault>=2.1",
  "pydantic>=2.10.3",
  "pyyaml>=6.0.2",
]

[project.urls]
homepage = "https://github.com/Behemyth/Household"
repository = "https://github.com/Behemyth/Household"

[dependency-groups]
lint = [
  "ansible_lint>=24.12.2",
  "ruff>=0.8.5",
  "mypy>=1.14",
]
test = [
  "molecule>=24.12.0",
  "pytest>=8.3.4",
  "pytest-mock>=3.14.0",
  "pytest_ansible>=24.12.0",
  "molecule-plugins[docker]>=23.6.0",
  "pytest-testinfra[ansible]>=10.1.0",
]

[tool.pytest.ini_options]
log_cli = true
markers = [
  "setup: Tests that should be run prior to any automation, verifying static IP setup",
]
testpaths = [
  "tests",
]

[tool.mypy]
exclude = "__pypackages__"
plugins = ["pydantic.mypy"]
strict = true

[tool.ruff]
line-length = 120
preview = true

[tool.ruff.lint]
ignore = [
  "D206",
  "D300",
  "D415",
  "E111",
  "E114",
  "E117",
]
select = [
  "D", # pydocstyle
  "F", # Pyflakes
  "I", # isort
  "PL", # pylint
  "UP", # pyupgrade
  "E", # pycodestyle
  "B", # flake8-bugbear
  "SIM", # flake8-simplify
  "PT", # flake8-pytest-style
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
docstring-code-format = true
indent-style = "space"
quote-style = "single"

[tool.coverage.report]
skip_empty = true

[tool.pdm.options]
update = ["--update-all"]

[tool.pdm.version]
source = "scm"

[tool.pdm.scripts]
analyze = {cmd = "ruff check tests"}
ansible-lint = {cmd = "ansible-lint"}
dev = {cmd = "molecule converge extensions"}
format = {cmd = "ruff format"}
lint = {composite = ["analyze", "format", "type-check", "ansible-lint"]}
test = {cmd = "pytest --verbose tests"}
type-check = {cmd = "mypy ."}

[build-system]
build-backend = "pdm.backend"
requires = ["pdm.backend"]
