version: '3.8'

services:
    reverse:
        image: jwilder/nginx-proxy:latest
        ports:
        - 80:80
        - 443:443
        volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro

    artifactory:
        environment:
            - VIRTUAL_HOST=conan.behemythic.com
        image: conanio/conan_server:latest
        ports:
            - 9300:9300

volumes:
    docker-data:
