version: '3.8'

services:
    reverse:
        image: jwilder/nginx-proxy:latest
        ports:
        - 80:80
        - 443:443
        volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro

    artifactory:
        environment:
            - VIRTUAL_HOST=artifactory.behemythic.com
            - VIRTUAL_PORT=8082
        image: docker.bintray.io/jfrog/artifactory-cpp-ce:latest
        volumes:
            - artifactory_data:/var/opt/jfrog/artifactory
        ports:
            - 8081:8081
            - 8082:8082

volumes:
    docker-data:
    artifactory_data:
