---
- name: Converge
  hosts: manager
  tasks:
    - name: Run playbook from manager
      ansible.builtin.command:
        cmd: ansible-playbook playbooks/init.yml
      become: true
      changed_when: true
