---
driver:
  name: vagrant
  provider:
    name: hyperv
platforms:
  - name: manager
    box: gutehall/ubuntu24-10
    memory: 4096
    cpus: 2
    interfaces:
      - network_name: private_network
        ip: 192.168.50.20
        guest: 80
        host: 8080
  - name: worker-1
    image: balenalib/raspberry-pi-node
  - name: worker-2
    image: balenalib/raspberry-pi-node
  - name: worker-3
    image: balenalib/raspberry-pi-node
  - name: worker-4
    image: balenalib/raspberry-pi-node
provisioner:
  name: ansible
  lint:
    name: ansible-lint

verifier:
  name: testinfra
