---
driver:
  name: docker
platforms:
  - name: manager
    image: ubuntu:24.10
  - name: worker-1
    image: balenalib/raspberry-pi-node
  - name: worker-2
    image: balenalib/raspberry-pi-node
  - name: worker-3
    image: balenalib/raspberry-pi-node
  - name: worker-4
    image: balenalib/raspberry-pi-node
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  # inventory:
  #   links:
  #     hosts: inventory.yml

verifier:
  name: ansible
