Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Use our public configuration file
  autoinstall_content = File.read(File.expand_path("../../../config/autoinstall.yml", __dir__))

  config.vm.define "manager" do |manager|
    manager.vm.box = "cloud-image/ubuntu-24.04"
    manager.vm.network "private_network", ip: "192.168.56.10"
    manager.vm.cloud_init do |cloud_init|
      cloud_init.content_type = "text/cloud-config"
      cloud_init.inline = autoinstall_content
    end
  end

  (1..4).each do |i|
    config.vm.define "worker-#{i}" do |worker|
      worker.vm.box = "cloud-image/ubuntu-24.04"
      worker.vm.network "private_network", ip: "192.168.56.1#{i}"
    end
  end
end