- name: Ethernet Connection 1
  community.general.nmcli:
    conn_name: Wired connection 1
    ifname: eth0
    type: ethernet
    ip4:
      - "{{ansible_host}}"
    gw4: 10.42.0.1
    dns4: ""
    routes4_extended:
      - ip: 10.42.0.1
        next_hop: 0.0.0.0
        mtu: 100
      - ip: 0.0.0.0/0
        next_hop: 10.42.0.1
        mtu: 100

    state: present

- name: Download and Install Fan Software
  shell: "curl https://download.argon40.com/argon1.sh | bash"
