all:
  children:
    manager:
      hosts:
        mini-behemyth:
      vars:
        ansible_host: 10.4.2.42
        ansible_user: asher
    nodes:
      hosts:
        mini-wumpus:
          ansible_host: 10.42.0.10
        mini-sota:
          ansible_host: 10.42.0.13
        mini-mush:
          ansible_host: 10.42.0.11
        mini-mouse:
          ansible_host: 10.42.0.12
      vars:
        ansible_user: synodic
        ansible_ssh_common_args: "-J asher@mini-behemyth"
