all:
  children:
    manager:
      hosts:
        behemythic.com:
      vars:
        ansible_user: asher
    nodes:
      hosts:
        mini-wumpus:
        mini-sota:
        mini-mush:
        mini-mouse:
      vars:
        ansible_user: synodic
        ansible_ssh_common_args: "-J behemythic.com"
