---
- name: Restart kea-dhcp4
  ansible.builtin.service:
    name: isc-kea-dhcp4-server.service
    state: restarted

- name: Reload kea-dhcp4
  ansible.builtin.service:
    name: isc-kea-dhcp4-server.service
    state: reloaded

- name: Restart kea-dhcp-ddns
  ansible.builtin.service:
    name: isc-kea-dhcp-ddns-server.service
    state: restarted

- name: Reload kea-dhcp-ddns
  ansible.builtin.service:
    name: isc-kea-dhcp-ddns-server.service
    state: reloaded

- name: Restart kea-ctrl-agent
  ansible.builtin.service:
    name: isc-kea-ctrl-agent.service
    state: restarted

- name: Reload kea-ctrl-agent
  ansible.builtin.service:
    name: isc-kea-ctrl-agent.service
    state: reloaded
