---
- name: Restart kea-dhcp4
  ansible.builtin.service:
    name: kea-dhcp4-server.service
    state: restarted

- name: Reload kea-dhcp4
  ansible.builtin.service:
    name: kea-dhcp4-server.service
    state: reloaded

- name: Restart kea-dhcp-ddns
  ansible.builtin.service:
    name: kea-dhcp-ddns-server.service
    state: restarted

- name: Reload kea-dhcp-ddns
  ansible.builtin.service:
    name: kea-dhcp-ddns-server.service
    state: reloaded
