- name: Remove Obsolete Packages
  become: true
  ansible.builtin.apt:
    state: absent
    pkg:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    force_apt_get: true

- name: Download Docker
  ansible.builtin.get_url:
    url: https://get.docker.com
    validate_certs: false
    dest: "{{ script_directory }}/get-docker.sh"
    mode: "0755"
    force: true

- name: Install Docker
  become: true
  ansible.builtin.shell: "{{ script_directory }}/get-docker.sh"

- name: Install Docker Python Module
  ansible.builtin.pip:
    name:
      - docker
    state: present
