- name: Update System Dependencies
  become: true
  ansible.builtin.apt:
    upgrade: true
    update_cache: true
    state: present

- name: Get Required Packages
  become: true
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - curl
      - python3-pip
      - ca-certificates
      - software-properties-common
      - gnupg
      - python3-venv
    update_cache: true
    state: present

- name: Install Python Packages
  ansible.builtin.pip:
    name:
      - pipx
    state: present

- name: Create Scripts Directory
  ansible.builtin.file:
    path: "{{ script_directory }}"
    state: directory
    mode: '0755'
