---
- name: Converge
  hosts: managers
  tasks:
    - name: Run the playbook as a command
      ansible.builtin.command:
        # This should match the 'run_ansible:' command in config/autoinstall.yml
        cmd: ansible-playbook --syntax-check playbooks/autoinstall.yml
        chdir: "/home/ansible/household"
      register: command_result
      changed_when: false
