---
- name: Converge
  hosts: managers
  tasks:
    - name: Run the playbook as a command
      ansible.builtin.command:
        cmd: ansible-playbook playbooks/autoinstall.yml
      changed_when: true
      register: command_result
