---
dependency:
  enabled: true
  name: galaxy
  options:
    requirements-file: requirements.yml
    role-file: requirements.yml

driver:
  name: docker

platforms:
  - name: manager
    image: geerlingguy/docker-ubuntu2404-ansible:latest
    pre_build_image: true
    # Give a read only volume of our repository location, mimicking autoinstall.yml
    volume:
      - /home/asher/ansible/collections/ansible_collections/synodic/infra:/home/ansible/household/:ro
    groups:
      - managers

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  scenario:
    name: autoinstall
  playbooks:
    prepare: ../resources/playbooks/prepare.yml
    verify: ../resources/playbooks/verify.yml
verifier:
  name: ansible
