---
dependency:
  enabled: true
  name: galaxy
  options:
    requirements-file: requirements.yml
    role-file: requirements.yml

driver:
  name: docker

platforms:
  - name: manager
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    groups:
      - managers

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  scenario:
    name: autoinstall
  playbooks:
    verify: ../resources/playbooks/verify.yml
  config:
    defautl:
      roles_path: ../../../../roles
verifier:
  name: ansible
