---
dependency:
  enabled: true
  name: galaxy
  options:
    requirements-file: requirements.yml
    role-file: requirements.yml

driver:
  name: docker

platforms:
  - name: manager
    image: ubuntu:oracular
    pre_build_image: true
    # Give a read only volume of our repository location, mimicking autoinstall.yml
    groups:
      - managers

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  scenario:
    name: autoinstall
  playbooks:
    verify: ../resources/playbooks/verify.yml
verifier:
  name: ansible
