---
# Molecule prepare playbook for the 'autoinstall' scenario
- name: Prepare
  hosts: managers
  become: true
  vars:
    description: |
      This scenario only verifies that the autoinstall playbook is present and can be parsed (syntax check), not executed.
  tasks:
    - name: Enable IPv4 Forwarding
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: 1
        state: present
        reload: true

    - name: Install Rsync
      ansible.builtin.apt:
        name: rsync
        state: present
        update_cache: true

    - name: Create Destination Folder
      ansible.builtin.file:
        path: /home/ansible/homelab
        state: directory
        mode: "0755"

    - name: Copy Repository Contents
      ansible.posix.synchronize:
        src: ../../../../
        dest: /home/ansible/homelab/
