---
- name: Prepare Managers
  hosts: managers
  become: true
  tasks:
    # Our cloud-init script will have already enabled IPv4 forwarding
    - name: Enable IPv4 forwarding
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: 1
        state: present
        reload: true

    - name: Install the rsync package
      ansible.builtin.apt:
        name: rsync
        state: present
        update_cache: true

    - name: Create the destination folder
      ansible.builtin.file:
        path: /home/ansible/homelab
        state: directory
        mode: "0755"

    - name: Copy the repository to where autoinstall.yml expects it
      ansible.posix.synchronize:
        src: /home/asher/ansible/collections/ansible_collections/synodic/infra/
        dest: /home/ansible/homelab/
