#cloud-config

# Run the cloud-init boot command before autoinstall starts its installation
bootcmd:
  - cat /proc/cmdline > /tmp/cmdline
  - sed -i'' 's/$/ autoinstall/g' /tmp/cmdline
  - mount -n --bind -o ro /tmp/cmdline /proc/cmdline
autoinstall:
  version: 1
  updates: all
  ansible:
    package_name: ansible-core
    install_method: pip
    run_user: synodic
    ansible_config:
    setup_controller:
      repositories:
        - path: /home/ansible/homelab/
          source: git@github.com:Behemyth/homelab.git
      run_ansible:
        - playbook_dir: /home/ansible/homelab
          playbook_name: playbooks/autoinstall.yml
          forks: 1
  network:
    version: 2
    # The manger device interfaces are enp1s0, enp2s0,... enp5s0
    ethernets:
      enp1s0:
        optional: false
        dhcp4: true
        nameservers:
          addresses:
            - 10.4.2.1
            - 8.8.8.8
            - 8.8.4.4
      switchports:
        match:
          name: enp*
        optional: true
    bridges:
      bridge0:
        interfaces: [switchports]
        optional: false
        addresses:
          - 10.42.0.1/24
  ssh:
    install-server: yes
    authorized-keys:
      - { { ds.meta_data.host_ssh_public } }
    allow-pw: no
  user-data:
    hostname: synodic
    manage_etc_hosts: true
    users:
      - name: synodic
        groups: users,admin,wheel
        shell: /bin/bash
        lock_passwd: true
        ssh_authorized_keys:
          - { { ds.meta_data.host_ssh_public } }
        sudo: ALL=(ALL) NOPASSWD:ALL

    ssh_keys:
      ed25519_private: { { ds.meta_data.shh_private } }
      ed25519_public: { { ds.meta_data.shh_public } }

    package_update: true
    ssh_pwauth: false
    ssh_deletekeys: false
    no_ssh_fingerprints: true
    ssh:
      emit_keys_to_console: false

    # Enable ipv4 forwarding
    write_files:
      - path: /etc/sysctl.d/enabled_ipv4_forwarding.conf
        content: |
          net.ipv4.conf.all.forwarding=1

    # The final action in cloud-init
    power_state:
      delay: 5
      mode: reboot
      message: Rebooting machine
