- name: Apply Network Config
  ansible.builtin.template:
    src: network.conf.j2
    dest: /etc/network/interfaces

- name: Install NetworkManager
  ansible.builtin.package:
    name: network-manager
    state: present

- name: Apply NetworkManager Config
  ansible.builtin.template:
    src: household.conf.j2
    dest: /etc/NetworkManager/conf.d/household.conf

- name: Service Start
  ansible.builtin.service:
    name: NetworkManager
    state: started
    enabled: true
