- name: Verify Mount Directory
  become: true
  ansible.builtin.file:
    path: /data/nfs-mount/portainer
    state: directory
    mode: "0777"

- name: Verify Stack Directory
  become: true
  ansible.builtin.file:
    path: /home/{{ansible_user}}/docker
    state: directory

- name: Create Stack File
  become: true
  ansible.builtin.template:
    src: portainer-stack.j2
    dest: /home/{{ansible_user}}/docker/portainer-stack.yml
    mode: "0775"

- name: Deploy the Stack
  community.docker.docker_stack:
    state: present
    name: portainer
    prune: true
    compose:
      - /home/{{ansible_user}}/docker/portainer-stack.yml
