---
dependency:
  enabled: true
  name: galaxy
  options:
    requirements-file: requirements.yml
    role-file: requirements.yml

driver:
  name: docker

platforms:
  - name: manager
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /sbin/init
    capabilities:
      - NET_ADMIN
    privileged: true
    docker_networks:
      - name: cluster_network
        driver: macvlan
        driver_options:
          parent: eth0
        ipam_config:
          - subnet: 10.42.0.0/24
    networks:
      - name: cluster_network
    groups:
      - managers

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  scenario:
    name: wsl
  config_options:
    defaults:
      stdout_callback: yaml

verifier:
  name: ansible
