---
dependency:
  enabled: true
  name: galaxy
  options:
    requirements-file: requirements.yml
    role-file: requirements.yml

driver:
  name: docker
  networks:
    - name: host_network
      driver: host
    - name: cluster_network
      driver: macvlan
      ipam:
        config:
          - subnet: 10.42.0.0/24
            gateway: 10.42.0.1
platforms:
  - name: manager
    image: geerlingguy/docker-ubuntu2404-ansible:latest
    pre_build_image: true
    network:
      - host_network
    groups:
      - managers

  - name: worker-1
    image: geerlingguy/docker-debian12-ansible:latest
    pre_build_image: true
    network:
      - cluster_network
    groups:
      - workers

  - name: worker-2
    image: geerlingguy/docker-debian12-ansible:latest
    pre_build_image: true
    network:
      - cluster_network
    groups:
      - workers

  - name: worker-3
    image: geerlingguy/docker-debian12-ansible:latest
    pre_build_image: true
    network:
      - cluster_network
    groups:
      - workers

  - name: worker-4
    image: geerlingguy/docker-debian12-ansible:latest
    pre_build_image: true
    network:
      - cluster_network
    groups:
      - workers

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  scenario:
    name: wsl
  playbooks:
    converge: ../resources/playbooks/converge.yml
    prepare: ../resources/playbooks/prepare.yml
    verify: ../resources/playbooks/verify.yml

verifier:
  name: ansible
