- name: Cluster Installation
  hosts: all
  tasks:
    # - name: Configure Tools
    #   ansible.builtin.import_role:
    #     name: default-install

    # - name: Setup Docker
    #   ansible.builtin.import_role:
    #     name: docker

- name: Manager Installation
  hosts: mini-behemyth
  # vars_files:
  #   - vars/azure.yml
  tasks:
    # - name: Register Swarm
    #   community.docker.docker_swarm:
    #     state: present
    #   register: swarm_info

    - name: Set IP Forwarding
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: "1"
        sysctl_set: true
        state: present
        reload: true

    # - name: Install Python Packages
    #   ansible.builtin.pip:
    #     name:
    #       - jsondiff
    #       - pyyaml
    #     state: present

    # - name: Setup Traefik
    #   ansible.builtin.import_role:
    #     name: traefik

    # - name: Setup NFS Server
    #   ansible.builtin.import_role:
    #     name: nfs-server

    # - name: Setup NFS Client
    #   ansible.builtin.import_role:
    #     name: nfs-client

- name: Node Installation
  hosts: workers
  tasks:
    # - name: Join swarm as worker node
    #   community.docker.docker_swarm:
    #     state: join
    #     advertise_addr: "{{ inventory_hostname }}"
    #     join_token: "{{ hostvars['mini-behemyth']['swarm_info']['swarm_facts']['JoinTokens']['Worker'] }}"
    #     remote_addrs: ["10.42.0.1:2377"]

    # - name: Setup NFS Client
    #   ansible.builtin.import_role:
    #     name: nfs-client
# - name: Cluster Stacks
#   hosts: mini-behemyth
#   tasks:
#     - name: Setup Portainer
#       ansible.builtin.import_role:
#         name: portainer

#     - name: Setup Artifactory
#       ansible.builtin.import_role:
#         name: artifactory
