- name: Cluster Installation
  hosts: all
  tasks:
    - name: Configure Tools
      ansible.builtin.import_role:
        name: default-install

    - name: Setup Docker
      ansible.builtin.import_role:
        name: docker-setup
