- name: Cluster Installation
  hosts: all
  tasks:
    - name: Configure Tools
      ansible.builtin.import_role:
        name: default-install

    - name: Setup Docker
      ansible.builtin.import_role:
        name: docker-setup

- name: Install Docker for Managers
  hosts: manager
  tasks:
    - name: Get Docker
      become: true
      ansible.builtin.apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - docker-buildx-plugin
          - docker-compose-plugin
        update_cache: true
        state: present

- name: Install Docker for Nodes
  hosts: nodes
  tasks:
    - name: Get Docker
      become: true
      ansible.builtin.apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - docker-buildx-plugin
          - docker-compose-plugin
        update_cache: true
        state: present
