---
- name: Initialize Self
  # We target ourselves when running the playbook because we are started via cloud-init
  hosts: localhost
  tasks:
    - name: Init as Manager
      ansible.builtin.include_role:
        name: synodic.infra.init_manager
        tasks_from: main.yml
