---
- name: Test new role from within this playbook
  hosts: managers
  tasks:
    - name: Testing role
      ansible.builtin.include_role:
        name: synodic.infra.update_manager
        tasks_from: main.yml
