name: Ansible Deployment

on:
  push:
    branches: [stable]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-host: ${{ secrets.HOST }}

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          directory: playbook
          playbook: site.yml
          vault_password: ${{secrets.VAULT_PASSWORD}}
          options: |
            --inventory inventory/hosts.yml
